In [2]:
import pandas as pd
import numpy as np
import json
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries loaded successfully.")

Libraries loaded successfully.

In [3]:
# Project paths
BASE_DIR = Path("..")
RAW_DIR = BASE_DIR / "data" / "raw"

# Load datasets
df_school = pd.read_csv(RAW_DIR / "track4_school_master.csv")
df_attendance = pd.read_csv(RAW_DIR / "track4_student_attendance.csv")
df_mdm = pd.read_excel(RAW_DIR / "track4_mid_day_meal_procurement.xlsx")
df_infra = pd.read_csv(RAW_DIR / "track4_school_infrastructure.csv")

with open(RAW_DIR / "track4_test_scores.json", "r", encoding="utf-8") as f:
    test_scores_data = json.load(f)

df_scores = pd.DataFrame(test_scores_data)

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [4]:
datasets = {
    "School Master": df_school,
    "Attendance": df_attendance,
    "MDM Procurement": df_mdm,
    "Test Scores": df_scores,
    "Infrastructure": df_infra
}

for name, df in datasets.items():
    print("=" * 60)
    print(name)
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    print()
    print(df.head(3))
    print()

============================================================
School Master
Shape: (618, 7)
Columns: ['school_id', 'school_name', 'district', 'block', 'total_enrolled_students', 'school_type', 'medium']

  school_id                         school_name   district          block  \
0   SCH0050  Govt. Senior Secondary School Tank       Moga         Moga-I
1   SCH0583            Govt. Middle School Dara  Ferozepur          Makhu
2   SCH0083          Govt. Primary School Dutta   Bathinda  Talwandi Sabo

   total_enrolled_students       school_type   medium
0                      424         Secondary  Punjabi
1                      436  Higher Secondary  Punjabi
2                      196           Primary    Hindi

============================================================
Attendance
Shape: (20800, 8)
Columns: ['record_id', 'date', 'school_id', 'grade', 'total_students', 'present_students', 'teacher_present', 'marked_by']

    record_id        date school_id grade  total_students  present_students  \
0  ATT0014650  07-26-2025  SCH-0596     5              85                60
1  ATT0009232  03.11.2025  sch_0054     I             197               119
2  ATT0006474  05-16-2025  SCH-0433     5              58                52

  teacher_present      marked_by
0            True          Admin
1            True          Admin
2       Available  Class Teacher

============================================================
MDM Procurement
Shape: (12360, 9)
Columns: ['procurement_id', 'date', 'school_id', 'vendor_name', 'grain_type', 'quantity', 'unit', 'total_cost', 'payment_status']

  procurement_id        date school_id          vendor_name grain_type  \
0      MDM008522  2026/01/14   SCH0249       Singh Brothers      WHEAT
1      MDM010158  2025-08-10   SCH0140  kumar general store      gehun
2      MDM007882  03/11/2025  SCH-0514  kumar general store        Oil

  quantity unit total_cost payment_status
0      NaN  NaN      336/-        PENDING
1     40.7  KGS       1221        Cleared
2     54.2  KGS       6504           Paid

============================================================
Test Scores
Shape: (8000, 9)
Columns: ['assessment_id', 'date', 'school_id', 'grade', 'subject', 'grading_scale', 'avg_score', 'max_marks', 'total_students_assessed']

  assessment_id         date school_id grade  subject grading_scale avg_score  \
0     TST005495   2025/05/05   sch0083     8  English  Letter Grade         C
1     TST003026   01.07.2025   sch0103     5  Punjabi           pct     63.4%
2     TST006793  06-Mar-2026  sch_0147     7     Math          CGPA       7.7

  max_marks  total_students_assessed
0        NA                      125
1       100                       76
2        10                      123

============================================================
Infrastructure
Shape: (3150, 10)
Columns: ['inspection_id', 'date', 'school_id', 'has_electricity', 'has_drinking_water', 'has_functional_toilet', 'has_boundary_wall', 'has_playground', 'inspector_name', 'remarks']

  inspection_id        date school_id has_electricity has_drinking_water  \
0     INSP02966  2025/04/02  sch_0476               H               True
1     INSP00970  13.05.2025   SCH0337            True               True
2     INSP01386  2025/06/26   SCH0127            True               True

  has_functional_toilet has_boundary_wall has_playground   inspector_name  \
0                  True               Yes            NaN   Fariq Tripathi
1                   Yes              True              H  Unnati Kulkarni
2                 False           Working     Functional       Girik Natt

          remarks
0  Good condition
1  Good condition
2  Toilets locked

In [5]:
# ============================================
# STEP 3: DATA QUALITY AUDIT
# ============================================

for name, df in datasets.items():

    print("\n" + "=" * 70)
    print(f"DATASET: {name}")
    print("=" * 70)

    print(f"Rows: {df.shape[0]:,}")
    print(f"Columns: {df.shape[1]}")

    print("\nData Types:")
    print(df.dtypes.to_string())

    print("\nMissing Values:")
    missing = df.isnull().sum()
    missing = missing[missing > 0]

    if len(missing) > 0:
        print(missing.to_string())
    else:
        print("No missing values")

    print("\nDuplicate Rows:", df.duplicated().sum())

    print("\nFirst 3 Rows:")
    print(df.head(3).to_string(index=False))

======================================================================
DATASET: School Master
======================================================================
Rows: 618
Columns: 7

Data Types:
school_id                  object
school_name                object
district                   object
block                      object
total_enrolled_students     int64
school_type                object
medium                     object

Missing Values:
district    23
block       64

Duplicate Rows: 18

First 3 Rows:
school_id                        school_name  district         block  total_enrolled_students      school_type  medium
  SCH0050 Govt. Senior Secondary School Tank      Moga        Moga-I                      424        Secondary Punjabi
  SCH0583           Govt. Middle School Dara Ferozepur         Makhu                      436 Higher Secondary Punjabi
  SCH0083         Govt. Primary School Dutta  Bathinda Talwandi Sabo                      196          Primary   Hindi

======================================================================
DATASET: Attendance
======================================================================
Rows: 20,800
Columns: 8

Data Types:
record_id           object
date                object
school_id           object
grade               object
total_students       int64
present_students     int64
teacher_present     object
marked_by           object

Missing Values:
record_id           425
teacher_present    1025
marked_by          3484

Duplicate Rows: 800

First 3 Rows:
 record_id       date school_id grade  total_students  present_students teacher_present     marked_by
ATT0014650 07-26-2025  SCH-0596     5              85                60            True         Admin
ATT0009232 03.11.2025  sch_0054     I             197               119            True         Admin
ATT0006474 05-16-2025  SCH-0433     5              58                52       Available Class Teacher

======================================================================
DATASET: MDM Procurement
======================================================================
Rows: 12,360
Columns: 9

Data Types:
procurement_id    object
date              object
school_id         object
vendor_name       object
grain_type        object
quantity          object
unit              object
total_cost        object
payment_status    object

Missing Values:
quantity          1909
unit              3804
total_cost         646
payment_status    1719

Duplicate Rows: 360

First 3 Rows:
procurement_id       date school_id         vendor_name grain_type quantity unit total_cost payment_status
     MDM008522 2026/01/14   SCH0249      Singh Brothers      WHEAT      NaN  NaN      336/-        PENDING
     MDM010158 2025-08-10   SCH0140 kumar general store      gehun     40.7  KGS       1221        Cleared
     MDM007882 03/11/2025  SCH-0514 kumar general store        Oil     54.2  KGS       6504           Paid

======================================================================
DATASET: Test Scores
======================================================================
Rows: 8,000
Columns: 9

Data Types:
assessment_id              object
date                       object
school_id                  object
grade                      object
subject                    object
grading_scale              object
avg_score                  object
max_marks                  object
total_students_assessed     int64

Missing Values:
No missing values

Duplicate Rows: 0

First 3 Rows:
assessment_id        date school_id grade subject grading_scale avg_score max_marks  total_students_assessed
    TST005495  2025/05/05   sch0083     8 English  Letter Grade         C        NA                      125
    TST003026  01.07.2025   sch0103     5 Punjabi           pct     63.4%       100                       76
    TST006793 06-Mar-2026  sch_0147     7    Math          CGPA       7.7        10                      123

======================================================================
DATASET: Infrastructure
======================================================================
Rows: 3,150
Columns: 10

Data Types:
inspection_id            object
date                     object
school_id                object
has_electricity          object
has_drinking_water       object
has_functional_toilet    object
has_boundary_wall        object
has_playground           object
inspector_name           object
remarks                  object

Missing Values:
has_electricity          170
has_drinking_water       146
has_functional_toilet    140
has_boundary_wall        177
has_playground           146
inspector_name           332
remarks                  513

Duplicate Rows: 150

First 3 Rows:
inspection_id       date school_id has_electricity has_drinking_water has_functional_toilet has_boundary_wall has_playground  inspector_name        remarks
    INSP02966 2025/04/02  sch_0476               H               True                  True               Yes            NaN  Fariq Tripathi Good condition
    INSP00970 13.05.2025   SCH0337            True               True                   Yes              True              H Unnati Kulkarni Good condition
    INSP01386 2025/06/26   SCH0127            True               True                 False           Working     Functional      Girik Natt Toilets locked

In [6]:
# ============================================
# CHECK IMPORTANT CATEGORICAL COLUMNS
# ============================================

print("SCHOOL MASTER")
print("-" * 50)

for col in ["district", "block", "school_type", "medium"]:
    if col in df_school.columns:
        print(f"\n{col}:")
        print(df_school[col].value_counts(dropna=False).to_string())


print("\n\nATTENDANCE")
print("-" * 50)

for col in ["grade", "teacher_present", "marked_by"]:
    if col in df_attendance.columns:
        print(f"\n{col}:")
        print(df_attendance[col].value_counts(dropna=False).to_string())


print("\n\nINFRASTRUCTURE")
print("-" * 50)

for col in df_infra.columns:
    if col != "school_id":
        print(f"\n{col}:")
        print(df_infra[col].value_counts(dropna=False).to_string())

SCHOOL MASTER
--------------------------------------------------

district:
district
Ferozepur    79
Bathinda     75
Sangrur      72
Amritsar     72
Ludhiana     71
Moga         70
Patiala      66
Jalandhar    63
NaN          23
patiala       8
ludhiana      5
bathinda      3
amritsar      3
sangrur       2
ferozepur     2
moga          2
jalandhar     2

block:
block
NaN                 64
Amritsar-II         26
Makhu               26
Maur                22
Talwandi Sabo       22
Ludhiana-II         22
Sunam               21
Samana              21
Nihal Singh Wala    20
Rajpura             20
Tarn Taran          19
Bagha Purana        19
Zira                18
Moga-I              17
Rampura Phul        17
Jalandhar-I         17
Amritsar-I          17
Dhuri               17
Nakodar             17
Machhiwara          16
Nabha               16
Ferozepur           16
Doraha              15
Bathinda            15
Phillaur            15
Ludhiana-I          14
Sangrur             14
Moga-II             14
Malerkotla          14
Patiala             14
Mamdot              13
Jalandhar-II        11
Ajnala               9

school_type:
school_type
Higher Secondary    139
Upper Primary       137
Secondary           134
Primary             119
higher secondary     27
upper primary        24
primary              21
secondary            17

medium:
medium
hindi      139
punjabi    124
English    122
Hindi      120
Punjabi    113


ATTENDANCE
--------------------------------------------------

grade:
grade
2      1495
V      1448
4      1447
7      1433
I      1431
IV     1417
6      1408
8      1406
9      1372
3      1365
1      1359
III    1326
5      1319
II     1291
10     1283

teacher_present:
teacher_present
True             8272
False            1366
Y                1133
1                1128
Yes              1121
NaN              1025
Hai               920
haan              896
Haan              874
H                 843
Available         642
Working           602
Functional        590
Nahi hai          199
na                191
No                185
0                 175
Nahi              173
N                 173
Kharab             81
Under Repair       77
Broken             71
Not Available      63

marked_by:
marked_by
Headmaster       3499
HM               3494
NaN              3484
Admin            3480
Clerk            3476
Class Teacher    3367


INFRASTRUCTURE
--------------------------------------------------

inspection_id:

inspection_id
INSP00773    2
INSP02112    2
INSP00437    2
INSP02165    2
INSP01492    2
INSP01006    2
INSP02324    2
INSP01299    2
INSP01761    2
INSP01002    2
INSP00290    2
INSP00880    2
INSP01232    2
INSP00451    2
INSP02526    2
INSP01270    2
INSP01262    2
INSP02529    2
INSP02373    2
INSP01763    2
INSP00297    2
INSP00417    2
INSP00332    2
INSP00766    2
INSP01074    2
INSP00496    2
INSP00292    2
INSP00046    2
INSP02084    2
INSP00782    2
INSP01361    2
INSP01601    2
INSP01548    2
INSP01695    2
INSP00153    2
INSP01242    2
INSP02176    2
INSP02664    2
INSP01815    2
INSP01831    2
INSP01412    2
INSP00001    2
INSP01584    2
INSP01227    2
INSP02777    2
INSP00409    2
INSP00473    2
INSP01065    2
INSP01118    2
INSP02987    2
INSP00103    2
INSP00267    2
INSP00197    2
INSP01818    2
INSP02013    2
INSP02255    2
INSP02739    2
INSP02343    2
INSP00015    2
INSP00094    2
INSP01201    2
INSP00913    2
INSP00728    2
INSP00747    2
INSP00195    2
INSP01583    2
INSP02415    2
INSP01269    2
INSP02725    2
INSP00045    2
INSP02333    2
INSP00901    2
INSP01091    2
INSP02175    2
INSP00928    2
INSP02226    2
INSP01966    2
INSP01271    2
INSP00322    2
INSP01802    2
INSP01821    2
INSP02426    2
INSP01764    2
INSP01642    2
INSP02273    2
INSP00719    2
INSP00522    2
INSP01331    2
INSP00756    2
INSP00696    2
INSP01375    2
INSP01666    2
INSP02632    2
INSP00645    2
INSP02679    2
INSP02419    2
INSP00175    2
INSP00315    2
INSP01799    2
INSP00323    2
INSP01196    2
INSP00843    2
INSP02902    2
INSP00686    2
INSP02568    2
INSP01191    2
INSP00863    2
INSP00204    2
INSP02292    2
INSP00299    2
INSP00052    2
INSP00394    2
INSP00064    2
INSP02780    2
INSP02145    2
INSP01317    2
INSP02506    2
INSP00930    2
INSP01726    2
INSP00053    2
INSP00795    2
INSP02968    2
INSP00271    2
INSP00252    2
INSP02378    2
INSP01843    2
INSP01360    2
INSP01771    2
INSP02133    2
INSP00507    2
INSP01273    2
INSP02483    2
INSP02114    2
INSP02046    2
INSP01942    2
INSP02852    2
INSP02910    2
INSP02604    2
INSP02896    2
INSP01992    2
INSP01608    2
INSP01922    2
INSP02580    2
INSP02002    2
INSP02882    2
INSP02749    2
INSP02478    2
INSP02547    2
INSP00613    2
INSP00145    2
INSP00748    1
INSP02301    1
INSP00022    1
INSP00460    1
INSP01185    1
INSP02325    1
INSP00956    1
INSP01216    1
INSP02434    1
INSP02854    1
INSP00970    1
INSP02552    1
INSP00219    1
INSP02177    1
INSP00818    1
INSP00602    1
INSP00018    1
INSP00171    1
INSP01738    1
INSP02283    1
INSP02803    1
INSP01408    1
INSP00179    1
INSP01337    1
INSP02205    1
INSP02746    1
INSP01663    1
INSP02025    1
INSP02771    1
INSP02097    1
INSP00135    1
INSP02846    1
INSP00415    1
INSP02697    1
INSP01484    1
INSP01188    1
INSP01730    1
INSP02006    1
INSP02154    1
INSP02572    1
INSP01147    1
INSP00310    1
INSP02274    1
INSP02440    1
INSP00193    1
INSP00777    1
INSP01678    1
INSP01236    1
INSP01394    1
INSP01765    1
INSP00946    1
INSP02052    1
INSP00830    1
INSP02967    1
INSP02922    1
INSP01279    1
INSP02900    1
INSP02808    1
INSP00486    1
INSP02372    1
INSP00443    1
INSP02598    1
INSP01714    1
INSP02982    1
INSP00757    1
INSP01881    1
INSP00241    1
INSP02355    1
INSP02431    1
INSP01744    1
INSP00140    1
INSP00347    1
INSP01537    1
INSP01743    1
INSP01682    1
INSP01460    1
INSP02034    1
INSP00257    1
INSP02300    1
INSP01732    1
INSP02601    1
INSP01785    1
INSP00215    1
INSP02497    1
INSP02801    1
INSP01358    1
INSP00300    1
INSP00433    1
INSP01101    1
INSP02078    1
INSP01252    1
INSP01075    1
INSP01588    1
INSP01289    1
INSP01675    1
INSP01448    1
INSP02897    1
INSP00071    1
INSP00643    1
INSP02543    1
INSP00945    1
INSP02539    1
INSP01106    1
INSP01175    1
INSP02670    1
INSP01757    1
INSP00479    1
INSP02178    1
INSP02429    1
INSP00730    1
INSP02282    1
INSP01092    1
INSP01420    1
INSP02443    1
INSP00808    1
INSP00464    1
INSP02699    1
INSP00568    1
INSP01611    1
INSP00077    1
INSP00612    1
INSP00786    1
INSP02908    1
INSP00344    1
INSP02171    1
INSP01560    1
INSP00545    1
INSP01024    1
INSP01981    1
INSP01323    1
INSP01019    1
INSP02182    1
INSP01463    1
INSP00622    1
INSP02837    1
INSP01967    1
INSP02845    1
INSP01622    1
INSP01367    1
INSP00888    1
INSP01845    1
INSP00033    1
INSP00212    1
INSP02551    1
INSP01256    1
INSP01398    1
INSP02819    1
INSP00355    1
INSP00150    1
INSP00255    1
INSP02030    1
INSP00599    1
INSP00185    1
INSP00579    1
INSP01174    1
INSP02252    1
INSP00472    1
INSP01964    1
INSP01303    1
INSP02998    1
INSP00258    1
INSP00933    1
INSP01685    1
INSP00597    1
INSP00611    1
INSP02326    1
INSP01507    1
INSP02488    1
INSP01887    1
INSP01339    1
INSP02612    1
INSP01392    1
INSP02249    1
INSP00121    1
INSP02893    1
INSP00529    1
INSP00904    1
INSP02916    1
INSP00440    1
INSP01379    1
INSP02773    1
INSP00189    1
INSP01951    1
INSP01265    1
INSP02351    1
INSP01115    1
INSP00369    1
INSP00388    1
INSP01422    1
INSP00810    1
INSP01953    1
INSP00247    1
INSP01238    1
INSP02432    1
INSP01150    1
INSP02168    1
INSP00977    1
INSP02500    1
INSP00444    1
INSP02806    1
INSP00565    1
INSP02093    1
INSP00677    1
INSP02660    1
INSP01860    1
INSP02795    1
INSP00176    1
INSP00556    1
INSP02222    1
INSP01557    1
INSP02959    1
INSP02293    1
INSP01809    1
INSP00868    1
INSP02119    1
INSP00450    1
INSP01135    1
INSP01851    1
INSP00582    1
INSP02491    1
INSP02051    1
INSP01426    1
INSP02172    1
INSP00765    1
INSP02549    1
INSP00508    1
INSP01946    1
INSP02941    1
INSP00089    1
INSP02884    1
INSP01318    1
INSP02826    1
INSP00679    1
INSP00411    1
INSP00991    1
INSP00583    1
INSP02724    1
INSP00026    1
INSP02359    1
INSP02709    1
INSP01948    1
INSP02015    1
INSP02164    1
INSP01840    1
INSP01427    1
INSP01610    1
INSP00424    1
INSP01413    1
INSP00068    1
INSP02294    1
INSP01619    1
INSP02607    1
INSP00032    1
INSP00528    1
INSP02288    1
INSP00458    1
INSP02659    1
INSP02454    1
INSP02919    1
INSP02675    1
INSP00167    1
INSP00125    1
INSP02595    1
INSP00683    1
INSP02330    1
INSP00573    1
INSP01199    1
INSP01090    1
INSP02365    1
INSP02712    1
INSP01711    1
INSP02871    1
INSP02468    1
INSP00931    1
INSP00177    1
INSP00595    1
INSP01564    1
INSP02031    1
INSP02452    1
INSP00802    1
INSP00434    1
INSP00081    1
INSP02263    1
INSP01197    1
INSP02094    1
INSP02957    1
INSP01628    1
INSP00938    1
INSP02885    1
INSP00371    1
INSP01941    1
INSP01787    1
INSP01927    1
INSP01573    1
INSP02196    1
INSP00839    1
INSP02849    1
INSP01865    1
INSP00142    1
INSP01207    1
INSP01728    1
INSP01481    1
INSP01937    1
INSP01939    1
INSP00533    1
INSP02895    1
INSP02245    1
INSP00655    1
INSP02413    1
INSP00412    1
INSP00178    1
INSP02887    1
INSP02535    1
INSP01000    1
INSP02345    1
INSP00480    1
INSP00184    1
INSP01158    1
INSP00671    1
INSP00606    1
INSP02272    1
INSP00760    1
INSP02875    1
INSP00487    1
INSP01579    1
INSP01152    1
INSP02029    1
INSP02862    1
INSP00163    1
INSP01223    1
INSP01916    1
INSP01049    1
INSP00431    1
INSP01104    1
INSP00439    1
INSP01884    1
INSP01226    1
INSP02032    1
INSP01037    1
INSP01076    1
INSP01749    1
INSP00031    1
INSP02021    1
INSP02103    1
INSP00963    1
INSP02285    1
INSP00174    1
INSP02213    1
INSP00326    1
INSP01290    1
INSP00280    1
INSP02655    1
INSP02414    1
INSP01984    1
INSP00813    1
INSP01217    1
INSP02617    1
INSP00701    1
INSP00558    1
INSP01899    1
INSP02518    1
INSP01512    1
INSP00074    1
INSP00049    1
INSP00603    1
INSP00681    1
INSP01452    1
INSP01903    1
INSP02406    1
INSP01445    1
INSP02878    1
INSP01578    1
INSP00403    1
INSP01746    1
INSP02755    1
INSP01555    1
INSP02738    1
INSP01212    1
INSP02561    1
INSP02270    1
INSP02237    1
INSP01513    1
INSP02356    1
INSP01875    1
INSP01012    1
INSP01072    1
INSP00680    1
INSP01712    1
INSP00325    1
INSP00820    1
INSP01489    1
INSP01812    1
INSP00811    1
INSP01973    1
INSP02840    1
INSP02212    1
INSP01129    1
INSP00502    1
INSP02642    1
INSP02125    1
INSP02828    1
INSP00240    1
INSP00762    1
INSP01717    1
INSP01229    1
INSP01473    1
INSP00953    1
INSP02307    1
INSP01654    1
INSP01045    1
INSP01478    1
INSP00512    1
INSP02141    1
INSP00841    1
INSP02769    1
INSP00638    1
INSP01950    1
INSP02954    1
INSP01722    1
INSP00600    1
INSP01475    1
INSP02135    1
INSP02602    1
INSP00109    1
INSP02401    1
INSP00319    1
INSP02983    1
INSP01095    1
INSP00569    1
INSP02687    1
INSP02298    1
INSP02872    1
INSP01546    1
INSP02974    1
INSP01925    1
INSP02692    1
INSP02805    1
INSP01469    1
INSP00057    1
INSP01789    1
INSP02275    1
INSP02131    1
INSP02197    1
INSP00469    1
INSP01886    1
INSP00941    1
INSP00536    1
INSP01428    1
INSP00555    1
INSP02621    1
INSP02211    1
INSP02536    1
INSP00692    1
INSP00070    1
INSP02764    1
INSP01740    1
INSP02122    1
INSP01004    1
INSP01254    1
INSP00566    1
INSP00314    1
INSP00234    1
INSP02381    1
INSP00735    1
INSP01378    1
INSP00112    1
INSP01345    1
INSP01506    1
INSP01053    1
INSP02321    1
INSP02043    1
INSP01377    1
INSP01614    1
INSP01178    1
INSP01753    1
INSP01374    1
INSP02210    1
INSP01341    1
INSP02003    1
INSP01300    1
INSP00362    1
INSP00136    1
INSP01591    1
INSP02286    1
INSP00860    1
INSP02380    1
INSP00367    1
INSP01867    1
INSP00030    1
INSP00023    1
INSP02507    1
INSP01134    1
INSP01035    1
INSP00421    1
INSP01538    1
INSP00461    1
INSP00044    1
INSP00088    1
INSP01125    1
INSP01772    1
INSP01018    1
INSP00283    1
INSP00694    1
INSP02990    1
INSP00534    1
INSP01179    1
INSP02581    1
INSP00790    1
INSP02482    1
INSP02516    1
INSP02228    1
INSP00875    1
INSP01042    1
INSP00791    1
INSP02816    1
INSP01566    1
INSP02311    1
INSP02190    1
INSP02305    1
INSP02989    1
INSP00222    1
INSP00544    1
INSP01424    1
INSP02259    1
INSP00706    1
INSP02466    1
INSP01007    1
INSP01794    1
INSP02782    1
INSP02930    1
INSP00979    1
INSP01905    1
INSP00273    1
INSP00523    1
INSP01069    1
INSP02068    1
INSP00351    1
INSP02248    1
INSP01850    1
INSP02439    1
INSP00652    1
INSP01808    1
INSP02726    1
INSP02528    1
INSP01346    1
INSP01079    1
INSP02745    1
INSP00169    1
INSP02636    1
INSP02924    1
INSP02070    1
INSP01934    1
INSP01638    1
INSP01838    1
INSP01376    1
INSP02354    1
INSP00220    1
INSP00368    1
INSP02804    1
INSP00950    1
INSP02399    1
INSP02253    1
INSP01457    1
INSP00352    1
INSP01098    1
INSP01264    1
INSP02239    1
INSP00491    1
INSP02827    1
INSP02494    1
INSP00499    1
INSP02789    1
INSP00211    1
INSP00898    1
INSP01205    1
INSP00651    1
INSP00228    1
INSP00366    1
INSP02223    1
INSP00277    1
INSP02099    1
INSP01114    1
INSP00737    1
INSP02575    1
INSP01994    1
INSP00408    1
INSP02417    1
INSP02458    1
INSP02247    1
INSP02531    1
INSP00008    1
INSP01533    1
INSP01801    1
INSP00416    1
INSP01607    1
INSP00840    1
INSP00865    1
INSP00200    1
INSP01117    1
INSP00284    1
INSP00232    1
INSP02992    1
INSP01081    1
INSP00097    1
INSP01508    1
INSP02760    1
INSP01813    1
INSP02936    1
INSP02587    1
INSP02720    1
INSP02556    1
INSP01890    1
INSP00105    1
INSP02350    1
INSP01928    1
INSP02715    1
INSP01124    1
INSP02009    1
INSP00806    1
INSP02409    1
INSP02582    1
INSP00745    1
INSP00227    1
INSP01222    1
INSP01293    1
INSP02421    1
INSP02092    1
INSP01030    1
INSP00890    1
INSP01617    1
INSP01111    1
INSP02116    1
INSP02763    1
INSP01043    1
INSP01777    1
INSP00465    1
INSP00882    1
INSP02156    1
INSP01423    1
INSP01243    1
INSP01768    1
INSP00213    1
INSP00013    1
INSP00423    1
INSP02368    1
INSP01054    1
INSP01230    1
INSP01456    1
INSP00742    1
INSP02776    1
INSP02700    1
INSP02329    1
INSP00799    1
INSP01432    1
INSP02427    1
INSP00510    1
INSP00598    1
INSP02714    1
INSP01162    1
INSP01362    1
INSP00858    1
INSP00519    1
INSP00965    1
INSP00574    1
INSP02865    1
INSP02544    1
INSP02107    1
INSP02754    1
INSP01308    1
INSP01587    1
INSP00124    1
INSP01498    1
INSP00221    1
INSP00359    1
INSP02530    1
INSP02113    1
INSP01796    1
INSP01698    1
INSP00260    1
INSP02913    1
INSP01351    1
INSP02517    1
INSP01107    1
INSP02532    1
INSP01878    1
INSP01657    1
INSP01094    1
INSP02856    1
INSP02449    1
INSP00457    1
INSP00463    1
INSP01692    1
INSP01668    1
INSP01414    1
INSP00382    1
INSP02939    1
INSP01534    1
INSP02473    1
INSP02442    1
INSP00966    1
INSP02842    1
INSP01778    1
INSP00943    1
INSP00060    1
INSP02391    1
INSP02859    1
INSP01766    1
INSP01576    1
INSP02484    1
INSP02411    1
INSP01028    1
INSP00658    1
INSP01314    1
INSP00846    1
INSP00543    1
INSP00870    1
INSP01710    1
INSP01310    1
INSP02227    1
INSP02579    1
INSP01447    1
INSP02644    1
INSP01656    1
INSP01504    1
INSP01085    1
INSP02379    1
INSP01433    1
INSP02546    1
INSP01892    1
INSP01062    1
INSP00436    1
INSP02474    1
INSP00238    1
INSP01488    1
INSP02728    1
INSP00110    1
INSP00164    1
INSP00289    1
INSP00253    1
INSP02127    1
INSP01739    1
INSP00768    1
INSP00788    1
INSP01443    1
INSP00927    1
INSP01836    1
INSP01287    1
INSP01554    1
INSP02457    1
INSP02230    1
INSP02752    1
INSP02313    1
INSP02563    1
INSP00848    1
INSP01438    1
INSP02541    1
INSP00462    1
INSP02357    1
INSP01603    1
INSP00158    1
INSP02523    1
INSP02087    1
INSP01805    1
INSP00678    1
INSP01874    1
INSP00239    1
INSP00980    1
INSP01221    1
INSP00244    1
INSP00101    1
INSP00316    1
INSP01011    1
INSP02584    1
INSP02583    1
INSP01056    1
INSP00262    1
INSP01834    1
INSP00196    1
INSP01980    1
INSP02950    1
INSP02384    1
INSP00180    1
INSP00835    1
INSP02441    1
INSP01581    1
INSP01038    1
INSP00341    1
INSP01180    1
INSP01988    1
INSP00749    1
INSP01193    1
INSP00663    1
INSP00481    1
INSP00804    1
INSP01455    1
INSP01499    1
INSP02562    1
INSP00550    1
INSP01741    1
INSP00784    1
INSP02848    1
INSP02314    1
INSP00743    1
INSP02578    1
INSP02611    1
INSP02085    1
INSP01781    1
INSP01128    1
INSP00248    1
INSP00872    1
INSP01026    1
INSP02955    1
INSP02860    1
INSP00627    1
INSP00348    1
INSP00279    1
INSP01989    1
INSP02404    1
INSP00656    1
INSP01357    1
INSP01033    1
INSP00908    1
INSP02761    1
INSP02721    1
INSP01136    1
INSP00912    1
INSP01908    1
INSP00633    1
INSP01103    1
INSP00446    1
INSP00618    1
INSP01363    1
INSP01748    1
INSP00845    1
INSP02685    1
INSP00548    1
INSP01979    1
INSP02179    1
INSP01058    1
INSP00264    1
INSP02996    1
INSP02477    1
INSP02024    1
INSP00354    1
INSP00803    1
INSP00209    1
INSP00614    1
INSP01048    1
INSP02158    1
INSP01676    1
INSP01272    1
INSP01954    1
INSP02693    1
INSP00058    1
INSP02348    1
INSP00812    1
INSP01552    1
INSP02737    1
INSP00562    1
INSP02310    1
INSP00230    1
INSP02640    1
INSP02033    1
INSP02933    1
INSP00539    1
INSP01736    1
INSP02576    1
INSP02229    1
INSP02870    1
INSP00561    1
INSP00708    1
INSP01235    1
INSP00425    1
INSP00648    1
INSP01883    1
INSP01324    1
INSP02596    1
INSP01160    1
INSP00621    1
INSP00554    1
INSP02802    1
INSP01558    1
INSP00999    1
INSP01365    1
INSP01755    1
INSP02886    1
INSP01645    1
INSP00441    1
INSP00509    1
INSP00590    1
INSP01237    1
INSP00650    1
INSP02041    1
INSP02683    1
INSP01335    1
INSP00631    1
INSP01403    1
INSP00483    1
INSP01245    1
INSP02571    1
INSP02231    1
INSP02096    1
INSP00857    1
INSP00531    1
INSP01996    1
INSP00050    1
INSP00859    1
INSP01073    1
INSP00720    1
INSP01826    1
INSP01430    1
INSP02370    1
INSP01449    1
INSP01633    1
INSP02244    1
INSP02888    1
INSP02744    1
INSP01544    1
INSP02167    1
INSP01792    1
INSP01393    1
INSP02257    1
INSP02766    1
INSP01651    1
INSP00298    1
INSP01327    1
INSP01458    1
INSP00959    1
INSP01321    1
INSP01609    1
INSP01214    1
INSP00350    1
INSP02565    1
INSP00644    1
INSP01897    1
INSP01284    1
INSP00670    1
INSP02537    1
INSP01643    1
INSP01955    1
INSP02591    1
INSP02499    1
INSP01553    1
INSP01715    1
INSP00787    1
INSP02833    1
INSP00141    1
INSP00789    1
INSP02688    1
INSP00715    1
INSP01466    1
INSP01718    1
INSP01627    1
INSP00619    1
INSP00407    1
INSP01519    1
INSP02017    1
INSP02937    1
INSP01780    1
INSP00498    1
INSP00343    1
INSP02879    1
INSP02390    1
INSP00783    1
INSP02291    1
INSP00304    1
INSP01952    1
INSP00665    1
INSP01814    1
INSP01624    1
INSP02836    1
INSP01629    1
INSP00085    1
INSP00942    1
INSP00962    1
INSP00842    1
INSP02502    1
INSP02651    1
INSP01415    1
INSP00291    1
INSP02195    1
INSP00605    1
INSP02150    1
INSP00917    1
INSP02622    1
INSP01823    1
INSP01100    1
INSP01089    1
INSP02214    1
INSP01442    1
INSP00822    1
INSP02597    1
INSP01001    1
INSP01495    1
INSP00019    1
INSP02975    1
INSP01126    1
INSP01352    1
INSP02251    1
INSP01396    1
INSP01719    1
INSP01594    1
INSP01810    1
INSP01658    1
INSP02128    1
INSP01518    1
INSP01010    1
INSP00361    1
INSP02690    1
INSP01841    1
INSP00345    1
INSP00987    1
INSP02026    1
INSP01912    1
INSP01476    1
INSP00114    1
INSP01211    1
INSP02023    1
INSP01895    1
INSP00086    1
INSP00669    1
INSP01015    1
INSP00129    1
INSP02498    1
INSP02961    1
INSP00892    1
INSP00308    1
INSP00384    1
INSP02044    1
INSP01296    1
INSP02067    1
INSP00427    1
INSP00495    1
INSP01208    1
INSP01209    1
INSP02317    1
INSP01400    1
INSP01767    1
INSP00276    1
INSP00490    1
INSP02667    1
INSP00691    1
INSP01798    1
INSP01770    1
INSP02258    1
INSP02868    1
INSP01059    1
INSP00119    1
INSP01025    1
INSP02784    1
INSP00282    1
INSP01672    1
INSP02459    1
INSP00969    1
INSP02064    1
INSP01919    1
INSP01790    1
INSP00156    1
INSP00305    1
INSP02054    1
INSP02684    1
INSP01690    1
INSP02781    1
INSP02360    1
INSP01526    1
INSP00576    1
INSP02065    1
INSP02705    1
INSP02759    1
INSP01322    1
INSP00844    1
INSP01407    1
INSP00270    1
INSP00630    1
INSP01034    1
INSP00287    1
INSP02331    1
INSP00301    1
INSP01510    1
INSP02020    1
INSP01868    1
INSP01468    1
INSP00066    1
INSP02340    1
INSP00891    1
INSP01879    1
INSP01972    1
INSP02657    1
INSP02976    1
INSP00231    1
INSP00504    1
INSP01353    1
INSP01511    1
INSP01613    1
INSP01005    1
INSP00837    1
INSP01724    1
INSP00375    1
INSP01399    1
INSP01993    1
INSP02012    1
INSP00752    1
INSP00100    1
INSP01923    1
INSP00867    1
INSP00911    1
INSP01477    1
INSP00530    1
INSP01261    1
INSP01832    1
INSP00637    1
INSP00186    1
INSP01382    1
INSP01568    1
INSP00932    1
INSP02877    1
INSP01559    1
INSP02810    1
INSP01274    1
INSP02180    1
INSP00608    1
INSP01503    1
INSP00152    1
INSP01437    1
INSP02260    1
INSP00732    1
INSP02857    1
INSP02869    1
INSP00024    1
INSP02627    1
INSP00159    1
INSP00862    1
INSP00903    1
INSP02981    1
INSP01231    1
INSP02377    1
INSP00445    1
INSP00755    1
INSP00924    1
INSP02988    1
INSP00312    1
INSP00549    1
INSP02105    1
INSP01625    1
INSP00307    1
INSP00288    1
INSP00695    1
INSP00309    1
INSP02444    1
INSP00750    1
INSP01602    1
INSP01691    1
INSP01577    1
INSP00909    1
INSP00087    1
INSP02504    1
INSP02958    1
INSP02624    1
INSP00971    1
INSP00014    1
INSP00874    1
INSP00809    1
INSP02711    1
INSP00515    1
INSP02779    1
INSP00410    1
INSP02010    1
INSP01338    1
INSP02383    1
INSP01462    1
INSP01371    1
INSP02807    1
INSP01585    1
INSP00383    1
INSP02016    1
INSP02663    1
INSP02496    1
INSP02462    1
INSP01848    1
INSP02059    1
INSP02629    1
INSP00553    1

In [7]:
# ============================================
# SCHOOL ID CONSISTENCY CHECK
# ============================================

print("School Master unique IDs:", df_school["school_id"].nunique())

print("Attendance unique IDs:", df_attendance["school_id"].nunique())

print("MDM unique IDs:", df_mdm["school_id"].nunique())

print("Infrastructure unique IDs:", df_infra["school_id"].nunique())

print("Scores unique IDs:", df_scores["school_id"].nunique())

School Master unique IDs: 600
Attendance unique IDs: 3443
MDM unique IDs: 3165
Infrastructure unique IDs: 1787
Scores unique IDs: 2800

# STEP- 4 CLEAN SCHOOL MASTER DATA

In [8]:
# ============================================
# STEP 4.1: CREATE WORKING COPIES
# ============================================

school = df_school.copy()
attendance = df_attendance.copy()
mdm = df_mdm.copy()
scores = df_scores.copy()
infra = df_infra.copy()

print("Working copies created.")

Working copies created.

In [9]:
# ============================================
# STEP 4.2: STANDARDIZE COLUMN NAMES
# ============================================

def clean_column_names(df):
    df = df.copy()
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )
    return df


school = clean_column_names(school)
attendance = clean_column_names(attendance)
mdm = clean_column_names(mdm)
scores = clean_column_names(scores)
infra = clean_column_names(infra)

print("Column names standardized.")

Column names standardized.

In [10]:
# ============================================
# STEP 4.3: STANDARDIZE SCHOOL IDs
# ============================================

def standardize_school_id(series):
    return (
        series
        .astype("string")
        .str.strip()
        .str.upper()
        .str.replace("-", "", regex=False)
        .str.replace("_", "", regex=False)
        .str.replace(" ", "", regex=False)
    )


for df in [school, attendance, mdm, scores, infra]:
    df["school_id"] = standardize_school_id(df["school_id"])


print("School IDs standardized.")

print("\nExample standardized IDs:")
print(school["school_id"].head(10).tolist())

School IDs standardized.

Example standardized IDs:
['SCH0050', 'SCH0583', 'SCH0083', 'SCH0306', 'SCH0110', 'SCH0011', 'SCH0269', 'SCH0354', 'SCH0329', 'SCH0534']

In [11]:
# ============================================
# STEP 4.4: REMOVE EXACT DUPLICATES
# ============================================

before = len(school)

school = school.drop_duplicates()

after = len(school)

print("School Master cleaning:")
print(f"Rows before removing duplicates: {before}")
print(f"Rows after removing duplicates:  {after}")
print(f"Duplicate rows removed:          {before - after}")

School Master cleaning:
Rows before removing duplicates: 618
Rows after removing duplicates:  600
Duplicate rows removed:          18

In [12]:
# ============================================
# STEP 4.5: NORMALIZE DISTRICT NAMES
# ============================================

school["district"] = (
    school["district"]
    .astype("string")
    .str.strip()
    .str.title()
)

print(school["district"].value_counts(dropna=False))

district
Ferozepur    79
Ludhiana     76
Bathinda     74
Amritsar     72
Patiala      72
Sangrur      72
Moga         71
Jalandhar    62
<NA>         22
Name: count, dtype: Int64

In [13]:
# ============================================
# STEP 4.6: NORMALIZE SCHOOL TYPE AND MEDIUM
# ============================================

school["school_type"] = (
    school["school_type"]
    .astype("string")
    .str.strip()
    .str.title()
)

school["medium"] = (
    school["medium"]
    .astype("string")
    .str.strip()
    .str.title()
)

print("School types:")
print(school["school_type"].value_counts(dropna=False))

print("\nMedium:")
print(school["medium"].value_counts(dropna=False))

School types:
school_type
Higher Secondary    161
Upper Primary       155
Secondary           148
Primary             136
Name: count, dtype: Int64

Medium:
medium
Hindi      254
Punjabi    226
English    120
Name: count, dtype: Int64

In [14]:
# ============================================
# STEP 4.7: CHECK MISSING VALUES
# ============================================

print("Missing values in School Master:")
print(school.isna().sum())

print("\nMissing value percentage:")
print((school.isna().mean() * 100).round(2))

Missing values in School Master:
school_id                   0
school_name                 0
district                   22
block                      61
total_enrolled_students     0
school_type                 0
medium                      0
dtype: int64

Missing value percentage:
school_id                   0.00
school_name                 0.00
district                    3.67
block                      10.17
total_enrolled_students     0.00
school_type                 0.00
medium                      0.00
dtype: float64

In [15]:
# ============================================
# STEP 4.8: HANDLE MISSING LOCATION VALUES
# ============================================

school["district"] = school["district"].fillna("Unknown")
school["block"] = school["block"].fillna("Unknown")

print("Missing values after handling:")
print(school.isna().sum())

Missing values after handling:
school_id                  0
school_name                0
district                   0
block                      0
total_enrolled_students    0
school_type                0
medium                     0
dtype: int64

In [16]:
# ============================================
# STEP 4.9: FINAL SCHOOL MASTER VALIDATION
# ============================================

print("Final School Master Validation")
print("-" * 40)

print("Total rows:", len(school))
print("Total columns:", len(school.columns))
print("Missing values:", school.isna().sum().sum())
print("Duplicate rows:", school.duplicated().sum())
print("Duplicate school IDs:", school["school_id"].duplicated().sum())

Final School Master Validation
----------------------------------------
Total rows: 600
Total columns: 7
Missing values: 0
Duplicate rows: 0
Duplicate school IDs: 0

In [17]:
# ============================================
# STEP 4.10: SAVE CLEANED SCHOOL MASTER
# ============================================

CLEANED_DIR = BASE_DIR / "data" / "cleaned"
CLEANED_DIR.mkdir(parents=True, exist_ok=True)

school.to_csv(
    CLEANED_DIR / "school_master_cleaned.csv",
    index=False
)

print("Cleaned School Master saved successfully.")
print("File:", CLEANED_DIR / "school_master_cleaned.csv")

Cleaned School Master saved successfully.
File: ..\data\cleaned\school_master_cleaned.csv

In [18]:
import os

file_path = CLEANED_DIR / "school_master_cleaned.csv"

print("File exists:", os.path.exists(file_path))
print("Rows:", len(pd.read_csv(file_path)))

File exists: True
Rows: 600

# CLEANING ATTENDENCE DATA

In [19]:
# ============================================
# ATTENDANCE CLEANING — START
# ============================================

attendance = df_attendance.copy()

print("Rows:", len(attendance))
print("Columns:", attendance.columns.tolist())

Rows: 20800
Columns: ['record_id', 'date', 'school_id', 'grade', 'total_students', 'present_students', 'teacher_present', 'marked_by']

In [20]:
# ============================================
# STEP 1: COMPLETE ATTENDANCE DATA AUDIT
# ============================================

print("========== DATASET OVERVIEW ==========")
print("Rows:", attendance.shape[0])
print("Columns:", attendance.shape[1])

print("\n========== COLUMN INFORMATION ==========")
print(attendance.info())

print("\n========== MISSING VALUES ==========")
print(attendance.isnull().sum())

print("\n========== MISSING VALUE % ==========")
print(
    (attendance.isnull().mean() * 100)
    .round(2)
    .sort_values(ascending=False)
)

print("\n========== DUPLICATE ROWS ==========")
print("Duplicate rows:", attendance.duplicated().sum())

print("\n========== UNIQUE VALUES ==========")
for column in attendance.columns:
    print(f"{column}: {attendance[column].nunique(dropna=True)} unique values")

print("\n========== FIRST 10 ROWS ==========")
display(attendance.head(10))

========== DATASET OVERVIEW ==========
Rows: 20800
Columns: 8

========== COLUMN INFORMATION ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   record_id         20375 non-null  object
 1   date              20800 non-null  object
 2   school_id         20800 non-null  object
 3   grade             20800 non-null  object
 4   total_students    20800 non-null  int64
 5   present_students  20800 non-null  int64
 6   teacher_present   19775 non-null  object
 7   marked_by         17316 non-null  object
dtypes: int64(2), object(6)
memory usage: 1.3+ MB
None

========== MISSING VALUES ==========
record_id            425
date                   0
school_id              0
grade                  0
total_students         0
present_students       0
teacher_present     1025
marked_by           3484
dtype: int64

========== MISSING VALUE % ==========
marked_by           16.75
teacher_present      4.93
record_id            2.04
date                 0.00
grade                0.00
school_id            0.00
present_students     0.00
total_students       0.00
dtype: float64

========== DUPLICATE ROWS ==========
Duplicate rows: 800

========== UNIQUE VALUES ==========
record_id: 19595 unique values
date: 2190 unique values
school_id: 3443 unique values
grade: 15 unique values
total_students: 261 unique values
present_students: 291 unique values
teacher_present: 22 unique values
marked_by: 5 unique values

========== FIRST 10 ROWS ==========

,record_id,date,school_id,grade,total_students,present_students,teacher_present,marked_by
0,ATT0014650,07-26-2025,SCH-0596,5,85,60,True,Admin
1,ATT0009232,03.11.2025,sch_0054,I,197,119,True,Admin
2,ATT0006474,05-16-2025,SCH-0433,5,58,52,Available,Class Teacher
3,ATT0018737,2025-04-21,SCH-0379,6,94,71,haan,NaN
4,ATT0012348,2025-08-30,SCH0208,I,234,194,True,Admin
5,ATT0017158,2025/05/19,sch0505,II,85,58,False,NaN
6,ATT0014975,04-15-2025,SCH0128,II,236,189,Yes,NaN
7,ATT0011151,2025-06-24,SCH0393,6,261,197,H,Admin
8,ATT0002175,17.05.2025,SCH0398,III,260,271,True,NaN
9,ATT0001505,2025-05-04,SCH-0377,8,151,125,True,Clerk

In [21]:
# ============================================
# STEP 2: DETAILED DATA AUDIT
# ============================================

print("========== DUPLICATE ROWS ==========")
print("Duplicate rows:", attendance.duplicated().sum())

print("\n========== UNIQUE VALUES ==========")

for column in attendance.columns:
    print(f"\n--- {column} ---")
    print("Unique:", attendance[column].nunique(dropna=True))
    
    # Show values only for categorical/object columns
    if attendance[column].dtype == "object":
        print(attendance[column].value_counts(dropna=False).head(30))

print("\n========== NUMERIC RANGE CHECK ==========")

print("\ntotal_students:")
print("Min:", attendance["total_students"].min())
print("Max:", attendance["total_students"].max())

print("\npresent_students:")
print("Min:", attendance["present_students"].min())
print("Max:", attendance["present_students"].max())

print("\nRecords where present_students > total_students:",
      (attendance["present_students"] > attendance["total_students"]).sum())

print("\nRecords where total_students <= 0:",
      (attendance["total_students"] <= 0).sum())

print("\nRecords where present_students < 0:",
      (attendance["present_students"] < 0).sum())

========== DUPLICATE ROWS ==========
Duplicate rows: 800

========== UNIQUE VALUES ==========

--- record_id ---
Unique: 19595
record_id
NaN           425
ATT0002175      2
ATT0011826      2
ATT0008214      2
ATT0000448      2
ATT0012292      2
ATT0012122      2
ATT0012784      2
ATT0000607      2
ATT0007459      2
ATT0007651      2
ATT0016144      2
ATT0003270      2
ATT0010677      2
ATT0000219      2
ATT0002749      2
ATT0004975      2
ATT0014901      2
ATT0008601      2
ATT0002713      2
ATT0009894      2
ATT0004668      2
ATT0011983      2
ATT0005100      2
ATT0001513      2
ATT0012567      2
ATT0002009      2
ATT0005710      2
ATT0001531      2
ATT0015216      2
Name: count, dtype: int64

--- date ---
Unique: 2190
date
2025-11-11     24
04/04/2025     24
03/10/2025     23
08/08/2025     23
2025-06-26     22
07/12/2025     22
2025-07-25     22
2026-01-27     21
2026-02-21     21
31-Dec-2025    21
28/04/2025     21
2026-03-31     20
02.07.2025     20
26/11/2025     20
2025-05-05     20
15-Feb-2026    20
2025-10-23     19
23/10/2025     19
16/02/2026     19
2025-07-05     19
23/03/2026     19
2026-01-14     18
08-11-2025     18
2025-06-06     18
04-Sep-2025    18
2025-11-06     18
05/05/2025     18
02-Sep-2025    18
21/03/2026     18
11/01/2026     18
Name: count, dtype: int64

--- school_id ---
Unique: 3443
school_id
SCH0202    30
SCH0205    28
SCH0394    27
SCH0337    27
SCH0546    27
SCH0568    26
SCH0584    26
SCH0182    26
SCH0201    25
SCH0440    25
SCH0166    25
SCH0208    24
SCH0515    24
SCH0373    24
SCH0320    24
SCH0378    24
SCH0178    24
SCH0180    24
SCH0368    24
SCH0474    24
SCH0547    24
SCH0347    24
SCH0007    24
SCH0012    24
SCH0268    24
SCH0064    24
SCH0191    24
SCH0400    24
SCH0519    24
SCH0537    23
Name: count, dtype: int64

--- grade ---
Unique: 15
grade
2      1495
V      1448
4      1447
7      1433
I      1431
IV     1417
6      1408
8      1406
9      1372
3      1365
1      1359
III    1326
5      1319
II     1291
10     1283
Name: count, dtype: int64

--- total_students ---
Unique: 261

--- present_students ---
Unique: 291

--- teacher_present ---
Unique: 22
teacher_present
True             8272
False            1366
Y                1133
1                1128
Yes              1121
NaN              1025
Hai               920
haan              896
Haan              874
H                 843
Available         642
Working           602
Functional        590
Nahi hai          199
na                191
No                185
0                 175
Nahi              173
N                 173
Kharab             81
Under Repair       77
Broken             71
Not Available      63
Name: count, dtype: int64

--- marked_by ---
Unique: 5
marked_by
Headmaster       3499
HM               3494
NaN              3484
Admin            3480
Clerk            3476
Class Teacher    3367
Name: count, dtype: int64

========== NUMERIC RANGE CHECK ==========

total_students:
Min: 40
Max: 300

present_students:
Min: 24
Max: 315

Records where present_students > total_students: 835

Records where total_students <= 0: 0

Records where present_students < 0: 0

In [22]:
# ============================================
# STEP 3: INSPECT IMPORTANT VALUES
# ============================================

print("========== RECORD ID ==========")
print("Missing:", attendance["record_id"].isna().sum())
print("Non-null duplicates:",
      attendance.loc[
          attendance["record_id"].notna(),
          "record_id"
      ].duplicated().sum())

print("\n========== DATES ==========")
print("Number of unique dates:", attendance["date"].nunique())
print("Sample raw dates:")
print(attendance["date"].drop_duplicates().head(30).to_list())

print("\n========== SCHOOL IDs ==========")
print("Unique school IDs:", attendance["school_id"].nunique())
print(attendance["school_id"].drop_duplicates().head(30).to_list())

print("\n========== GRADES ==========")
print(attendance["grade"].value_counts(dropna=False))

print("\n========== TEACHER PRESENT ==========")
print(attendance["teacher_present"].value_counts(dropna=False))

print("\n========== MARKED BY ==========")
print(attendance["marked_by"].value_counts(dropna=False))

print("\n========== ATTENDANCE LOGIC ==========")
invalid_present = (
    attendance["present_students"] >
    attendance["total_students"]
)

print("present > total:", invalid_present.sum())

print("\nSample invalid records:")
display(
    attendance.loc[
        invalid_present,
        [
            "record_id",
            "date",
            "school_id",
            "grade",
            "total_students",
            "present_students"
        ]
    ].head(10)
)

========== RECORD ID ==========
Missing: 425
Non-null duplicates: 780

========== DATES ==========
Number of unique dates: 2190
Sample raw dates:
['07-26-2025', '03.11.2025', '05-16-2025', '2025-04-21', '2025-08-30', '2025/05/19', '04-15-2025', '2025-06-24', '17.05.2025', '2025-05-04', '09.07.2025', '30/07/2025', '26/05/2025', '2025/10/30', '2025-09-20', '02-18-2026', '24/01/2026', '08/08/2025', '10/01/2026', '10.10.2025', '2025/12/04', '09/07/2025', '07.12.2025', '2025-08-05', '11-Sep-2025', '2025-10-23', '10-01-2025', '2025-11-09', '2025-10-27', '08-22-2025']

========== SCHOOL IDs ==========
Unique school IDs: 3443
['SCH-0596', 'sch_0054', 'SCH-0433', 'SCH-0379', 'SCH0208', 'sch0505', 'SCH0128', 'SCH0393', 'SCH0398', 'SCH-0377', 'SCH0268', '0286', 'SCH-0403', 'S0212', 'SCH0434', 'SCH0555', 'sch_0074', 'SCH0335', 'sch_0329', 'SCH0369', 'S0180', '0328', 'SCH-0188', 'SCH0352', 'S0217', 'SCH0454', 'SCH-0517', 'sch0451', 'SCH0598', 'SCH-0304']

========== GRADES ==========
grade
2      1495
V      1448
4      1447
7      1433
I      1431
IV     1417
6      1408
8      1406
9      1372
3      1365
1      1359
III    1326
5      1319
II     1291
10     1283
Name: count, dtype: int64

========== TEACHER PRESENT ==========
teacher_present
True             8272
False            1366
Y                1133
1                1128
Yes              1121
NaN              1025
Hai               920
haan              896
Haan              874
H                 843
Available         642
Working           602
Functional        590
Nahi hai          199
na                191
No                185
0                 175
Nahi              173
N                 173
Kharab             81
Under Repair       77
Broken             71
Not Available      63
Name: count, dtype: int64

========== MARKED BY ==========
marked_by
Headmaster       3499
HM               3494
NaN              3484
Admin            3480
Clerk            3476
Class Teacher    3367
Name: count, dtype: int64

========== ATTENDANCE LOGIC ==========
present > total: 835

Sample invalid records:

      record_id         date school_id grade  total_students  present_students
8    ATT0002175   17.05.2025   SCH0398   III             260               271
12   ATT0007459   26/05/2025  SCH-0403     8             181               188
55   ATT0010713   2025/08/17   SCH0235     V             299               315
100  ATT0003799   11.01.2026   SCH0225     I              92               104
132  ATT0007882   21/11/2025   SCH0136     6             137               145
142  ATT0015453   2025-06-30   SCH0202     9              56                69
149  ATT0012139   2026-01-25  SCH-0417     V             160               176
174  ATT0006557   11/08/2025     S0538     3             142               159
180         NaN  12-Jun-2025  sch_0231     3             128               139
196  ATT0005478   08.02.2026   SCH0305     I             209               225

In [23]:
# ============================================
# STEP 4: COMPLETE CATEGORICAL AUDIT
# ============================================

print("========== ALL GRADES ==========")
print(
    attendance["grade"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\n========== ALL TEACHER_PRESENT VALUES ==========")
print(
    attendance["teacher_present"]
    .value_counts(dropna=False)
)

print("\n========== ALL MARKED_BY VALUES ==========")
print(
    attendance["marked_by"]
    .value_counts(dropna=False)
)

print("\n========== SCHOOL ID FORMAT SAMPLE ==========")
print(
    attendance["school_id"]
    .drop_duplicates()
    .sort_values()
    .head(100)
    .to_list()
)

========== ALL GRADES ==========
grade
1      1359
10     1283
2      1495
3      1365
4      1447
5      1319
6      1408
7      1433
8      1406
9      1372
I      1431
II     1291
III    1326
IV     1417
V      1448
Name: count, dtype: int64

========== ALL TEACHER_PRESENT VALUES ==========
teacher_present
True             8272
False            1366
Y                1133
1                1128
Yes              1121
NaN              1025
Hai               920
haan              896
Haan              874
H                 843
Available         642
Working           602
Functional        590
Nahi hai          199
na                191
No                185
0                 175
Nahi              173
N                 173
Kharab             81
Under Repair       77
Broken             71
Not Available      63
Name: count, dtype: int64

========== ALL MARKED_BY VALUES ==========
marked_by
Headmaster       3499
HM               3494
NaN              3484
Admin            3480
Clerk            3476
Class Teacher    3367
Name: count, dtype: int64

========== SCHOOL ID FORMAT SAMPLE ==========
['0001', '0002', '0003', '0006', '0008', '0009', '0010', '0011', '0012', '0014', '0015', '0018', '0019', '0020', '0021', '0022', '0023', '0024', '0025', '0026', '0027', '0028', '0031', '0032', '0033', '0035', '0036', '0037', '0038', '0039', '0040', '0041', '0042', '0043', '0044', '0045', '0046', '0047', '0049', '0050', '0051', '0052', '0053', '0054', '0056', '0057', '0058', '0059', '0060', '0061', '0062', '0063', '0064', '0065', '0066', '0069', '0070', '0071', '0072', '0073', '0074', '0076', '0077', '0078', '0081', '0082', '0084', '0085', '0086', '0087', '0088', '0089', '0090', '0091', '0092', '0093', '0095', '0096', '0098', '0099', '0100', '0101', '0103', '0105', '0106', '0107', '0108', '0110', '0111', '0113', '0114', '0115', '0116', '0117', '0118', '0119', '0120', '0121', '0123', '0125']

In [24]:
# ============================================
# STEP 5: FULL VALUE AUDIT
# ============================================

print("========== TEACHER PRESENT ==========")
teacher_values = attendance["teacher_present"].value_counts(dropna=False)
print(teacher_values.to_string())

print("\n========== MARKED BY ==========")
marked_values = attendance["marked_by"].value_counts(dropna=False)
print(marked_values.to_string())

========== TEACHER PRESENT ==========
teacher_present
True             8272
False            1366
Y                1133
1                1128
Yes              1121
NaN              1025
Hai               920
haan              896
Haan              874
H                 843
Available         642
Working           602
Functional        590
Nahi hai          199
na                191
No                185
0                 175
Nahi              173
N                 173
Kharab             81
Under Repair       77
Broken             71
Not Available      63

========== MARKED BY ==========
marked_by
Headmaster       3499
HM               3494
NaN              3484
Admin            3480
Clerk            3476
Class Teacher    3367

In [25]:
# ============================================
# STEP 6: COMPLETE CATEGORY AUDIT
# ============================================

print("========== TEACHER PRESENT — ALL VALUES ==========")

teacher_unique = (
    attendance["teacher_present"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

for i, value in enumerate(sorted(teacher_unique, key=str.lower), start=1):
    print(f"{i:02d}. {repr(value)}")

print("\nTotal non-null unique values:", len(teacher_unique))


print("\n========== MARKED BY — ALL VALUES ==========")

marked_unique = (
    attendance["marked_by"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

for i, value in enumerate(sorted(marked_unique, key=str.lower), start=1):
    print(f"{i:02d}. {repr(value)}")

print("\nTotal non-null unique values:", len(marked_unique))

========== TEACHER PRESENT — ALL VALUES ==========
01. '0'
02. '1'
03. 'Available'
04. 'Broken'
05. 'False'
06. 'Functional'
07. 'H'
08. 'haan'
09. 'Haan'
10. 'Hai'
11. 'Kharab'
12. 'N'
13. 'na'
14. 'Nahi'
15. 'Nahi hai'
16. 'No'
17. 'Not Available'
18. 'True'
19. 'Under Repair'
20. 'Working'
21. 'Y'
22. 'Yes'

Total non-null unique values: 22

========== MARKED BY — ALL VALUES ==========
01. 'Admin'
02. 'Class Teacher'
03. 'Clerk'
04. 'Headmaster'
05. 'HM'

Total non-null unique values: 5

In [26]:
# ============================================
# STEP 7: CLEAN TEACHER PRESENT
# ============================================

teacher_present_map = {
    # Present
    "True": "Present",
    "Y": "Present",
    "Yes": "Present",
    "1": "Present",
    "Hai": "Present",
    "haan": "Present",
    "Haan": "Present",
    "H": "Present",
    "Available": "Present",
    "Working": "Present",
    "Functional": "Present",

    # Absent
    "False": "Absent",
    "N": "Absent",
    "No": "Absent",
    "0": "Absent",
    "na": "Absent",
    "Nahi": "Absent",
    "Nahi hai": "Absent",
    "Not Available": "Absent",

    # Problem / repair
    "Kharab": "Issue",
    "Broken": "Issue",
    "Under Repair": "Issue"
}

attendance["teacher_present_clean"] = (
    attendance["teacher_present"]
    .astype("string")
    .str.strip()
    .map(teacher_present_map)
    .fillna("Unknown")
)

print("========== CLEANED TEACHER PRESENT ==========")
print(attendance["teacher_present_clean"].value_counts())

print("\n========== UNMAPPED VALUES ==========")
unmapped = attendance.loc[
    ~attendance["teacher_present"].isna()
    & attendance["teacher_present_clean"].eq("Unknown"),
    "teacher_present"
].unique()

print(unmapped)

========== CLEANED TEACHER PRESENT ==========
teacher_present_clean
Present    17021
Absent      2525
Unknown     1025
Issue        229
Name: count, dtype: int64

========== UNMAPPED VALUES ==========
[]

In [27]:
# ============================================
# STEP 8: AUDIT MARKED BY
# ============================================

print("========== MARKED BY — COUNTS ==========")

print(
    attendance["marked_by"]
    .value_counts(dropna=False)
    .to_string()
)

print("\n========== MARKED BY — UNIQUE VALUES ==========")

marked_unique = (
    attendance["marked_by"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

for i, value in enumerate(sorted(marked_unique, key=str.lower), start=1):
    print(f"{i:02d}. {repr(value)}")

print("\nTotal non-null unique values:", len(marked_unique))

========== MARKED BY — COUNTS ==========
marked_by
Headmaster       3499
HM               3494
NaN              3484
Admin            3480
Clerk            3476
Class Teacher    3367

========== MARKED BY — UNIQUE VALUES ==========
01. 'Admin'
02. 'Class Teacher'
03. 'Clerk'
04. 'Headmaster'
05. 'HM'

Total non-null unique values: 5

In [28]:
# ============================================
# STEP 9: CLEAN MARKED BY
# ============================================

marked_by_map = {
    "HM": "Headmaster",
    "Headmaster": "Headmaster",
    "Admin": "Admin",
    "Clerk": "Clerk",
    "Class Teacher": "Class Teacher"
}

attendance["marked_by_clean"] = (
    attendance["marked_by"]
    .astype("string")
    .str.strip()
    .map(marked_by_map)
    .fillna("Unknown")
)

print("========== CLEANED MARKED BY ==========")
print(attendance["marked_by_clean"].value_counts())

print("\n========== UNMAPPED VALUES ==========")
unmapped = attendance.loc[
    ~attendance["marked_by"].isna()
    & attendance["marked_by_clean"].eq("Unknown"),
    "marked_by"
].unique()

print(unmapped)

========== CLEANED MARKED BY ==========
marked_by_clean
Headmaster       6993
Unknown          3484
Admin            3480
Clerk            3476
Class Teacher    3367
Name: count, dtype: int64

========== UNMAPPED VALUES ==========
[]

In [29]:
# ============================================
# STEP 10: STANDARDIZE ATTENDANCE DATES
# ============================================

import re
from datetime import datetime

def parse_attendance_date(value):
    if pd.isna(value):
        return pd.NaT

    value = str(value).strip()

    # ISO format: YYYY-MM-DD / YYYY/MM/DD / YYYY.MM.DD
    if re.match(r"^\d{4}[-/.]\d{1,2}[-/.]\d{1,2}$", value):
        return pd.to_datetime(value, format="mixed", errors="coerce")

    # Text month format: 11-Sep-2025
    if re.match(r"^\d{1,2}-[A-Za-z]{3}-\d{4}$", value):
        return pd.to_datetime(value, format="%d-%b-%Y", errors="coerce")

    # Numeric date formats
    parts = re.split(r"[-/.]", value)

    if len(parts) == 3:
        a, b, c = parts

        try:
            a, b, c = int(a), int(b), int(c)
        except ValueError:
            return pd.NaT

        # If first component is 4-digit year
        if len(str(parts[0])) == 4:
            return pd.to_datetime(
                f"{a}-{b:02d}-{c:02d}",
                format="%Y-%m-%d",
                errors="coerce"
            )

        # If first component > 12, it must be DD-MM-YYYY
        if a > 12:
            return pd.to_datetime(
                f"{c}-{b:02d}-{a:02d}",
                format="%Y-%m-%d",
                errors="coerce"
            )

        # If second component > 12, it must be MM-DD-YYYY
        if b > 12:
            return pd.to_datetime(
                f"{c}-{a:02d}-{b:02d}",
                format="%Y-%m-%d",
                errors="coerce"
            )

        # Ambiguous case: use month-first for consistency
        return pd.to_datetime(
            f"{c}-{a:02d}-{b:02d}",
            format="%Y-%m-%d",
            errors="coerce"
        )

    return pd.NaT


attendance["date_clean"] = attendance["date"].apply(parse_attendance_date)

print("========== DATE CLEANING AUDIT ==========")
print("Original rows:", len(attendance))
print("Valid dates:", attendance["date_clean"].notna().sum())
print("Invalid dates:", attendance["date_clean"].isna().sum())

print("\nDate range:")
print("Minimum:", attendance["date_clean"].min())
print("Maximum:", attendance["date_clean"].max())

print("\nMissing date values:", attendance["date_clean"].isna().sum())

print("\nSample standardized dates:")
display(
    attendance[["date", "date_clean"]]
    .drop_duplicates()
    .head(20)
)

========== DATE CLEANING AUDIT ==========
Original rows: 20800
Valid dates: 20800
Invalid dates: 0

Date range:
Minimum: 2025-01-04 00:00:00
Maximum: 2026-12-03 00:00:00

Missing date values: 0

Sample standardized dates:

          date date_clean
0   07-26-2025 2025-07-26
1   03.11.2025 2025-03-11
2   05-16-2025 2025-05-16
3   2025-04-21 2025-04-21
4   2025-08-30 2025-08-30
5   2025/05/19 2025-05-19
6   04-15-2025 2025-04-15
7   2025-06-24 2025-06-24
8   17.05.2025 2025-05-17
9   2025-05-04 2025-05-04
10  09.07.2025 2025-09-07
11  30/07/2025 2025-07-30
12  26/05/2025 2025-05-26
13  2025/10/30 2025-10-30
14  2025-09-20 2025-09-20
15  02-18-2026 2026-02-18
16  24/01/2026 2026-01-24
17  08/08/2025 2025-08-08
18  10/01/2026 2026-10-01
19  10.10.2025 2025-10-10

In [30]:
# ============================================
# STEP 11: SCHOOL ID NORMALIZATION AUDIT
# ============================================

import re

def normalize_school_id(value):
    if pd.isna(value):
        return pd.NA

    value = str(value).strip().upper()

    # Extract numeric part
    numbers = re.findall(r"\d+", value)

    if len(numbers) == 1:
        return f"SCH{int(numbers[0]):04d}"

    return pd.NA


attendance["school_id_clean"] = (
    attendance["school_id"]
    .apply(normalize_school_id)
)

print("========== SCHOOL ID NORMALIZATION AUDIT ==========")

print("Original unique school IDs:",
      attendance["school_id"].nunique())

print("Normalized unique school IDs:",
      attendance["school_id_clean"].nunique())

print("\nInvalid / unmapped IDs:",
      attendance["school_id_clean"].isna().sum())

print("\n========== RAW → CLEANED SAMPLE ==========")

display(
    attendance[["school_id", "school_id_clean"]]
    .drop_duplicates()
    .head(30)
)

print("\n========== NORMALIZED ID FREQUENCY ==========")

print(
    attendance["school_id_clean"]
    .value_counts()
    .head(20)
)

========== SCHOOL ID NORMALIZATION AUDIT ==========
Original unique school IDs: 3443
Normalized unique school IDs: 600

Invalid / unmapped IDs: 0

========== RAW → CLEANED SAMPLE ==========

   school_id school_id_clean
0   SCH-0596         SCH0596
1   sch_0054         SCH0054
2   SCH-0433         SCH0433
3   SCH-0379         SCH0379
4    SCH0208         SCH0208
5    sch0505         SCH0505
6    SCH0128         SCH0128
7    SCH0393         SCH0393
8    SCH0398         SCH0398
9   SCH-0377         SCH0377
10   SCH0268         SCH0268
11      0286         SCH0286
12  SCH-0403         SCH0403
13     S0212         SCH0212
14   SCH0434         SCH0434
15   SCH0555         SCH0555
16  sch_0074         SCH0074
17   SCH0335         SCH0335
18  sch_0329         SCH0329
19   SCH0369         SCH0369
20     S0180         SCH0180
21      0328         SCH0328
22  SCH-0188         SCH0188
23   SCH0352         SCH0352
24     S0217         SCH0217
25   SCH0454         SCH0454
26  SCH-0517         SCH0517
27   sch0451         SCH0451
28   SCH0598         SCH0598
29  SCH-0304         SCH0304

========== NORMALIZED ID FREQUENCY ==========
school_id_clean
SCH0202    53
SCH0540    52
SCH0586    52
SCH0536    51
SCH0394    51
SCH0405    49
SCH0588    49
SCH0546    49
SCH0205    49
SCH0484    49
SCH0534    48
SCH0474    48
SCH0028    48
SCH0337    48
SCH0084    47
SCH0555    47
SCH0309    47
SCH0317    47
SCH0385    47
SCH0147    47
Name: count, dtype: int64

In [31]:
# ============================================
# STEP 11B: VERIFY SCHOOL ID NORMALIZATION
# ============================================

print("Original unique school IDs:",
      attendance["school_id"].nunique())

print("Normalized unique school IDs:",
      attendance["school_id_clean"].nunique())

print("Invalid / unmapped IDs:",
      attendance["school_id_clean"].isna().sum())

print("\nRAW → CLEANED EXAMPLES:")

display(
    attendance[["school_id", "school_id_clean"]]
    .drop_duplicates()
    .sample(30, random_state=42)
)

Original unique school IDs: 3443
Normalized unique school IDs: 600
Invalid / unmapped IDs: 0

RAW → CLEANED EXAMPLES:

      school_id school_id_clean
970     SCH0355         SCH0355
51     SCH-0397         SCH0397
1464    SCH0281         SCH0281
649     SCH0205         SCH0205
3181   sch_0593         SCH0593
11201   sch0324         SCH0324
3633   sch_0336         SCH0336
3151    sch0205         SCH0205
11739   sch0195         SCH0195
3905       0396         SCH0396
372     SCH0220         SCH0220
14411   sch0255         SCH0255
8723       0090         SCH0090
4484       0021         SCH0021
1503      S0061         SCH0061
215    SCH-0061         SCH0061
3644      S0514         SCH0514
2121    SCH0238         SCH0238
15044      0259         SCH0259
1160    SCH0200         SCH0200
2334      S0358         SCH0358
9287   SCH-0597         SCH0597
1233   SCH-0298         SCH0298
257     SCH0007         SCH0007
5758   SCH-0562         SCH0562
32     SCH-0203         SCH0203
11081   sch0597         SCH0597
7316       0074         SCH0074
4658   sch_0102         SCH0102
16195      0221         SCH0221

In [32]:
# ============================================
# STEP 12: CROSS-CHECK SCHOOL IDs
# ============================================

master_ids = set(
    df_school["school_id"]
    .astype(str)
    .str.strip()
    .str.upper()
)

attendance_ids = set(
    attendance["school_id_clean"]
    .dropna()
    .astype(str)
)

matched_ids = attendance_ids.intersection(master_ids)
unmatched_ids = attendance_ids - master_ids

print("========== SCHOOL ID CROSS-CHECK ==========")

print("Unique attendance IDs:", len(attendance_ids))
print("School Master IDs:", len(master_ids))
print("Matched IDs:", len(matched_ids))
print("Unmatched attendance IDs:", len(unmatched_ids))

if unmatched_ids:
    print("\nUnmatched IDs:")
    print(sorted(unmatched_ids))
else:
    print("\nAll attendance school IDs exist in School Master.")

========== SCHOOL ID CROSS-CHECK ==========
Unique attendance IDs: 600
School Master IDs: 600
Matched IDs: 600
Unmatched attendance IDs: 0

All attendance school IDs exist in School Master.

In [33]:
# ============================================
# STEP 13: GRADE NORMALIZATION
# ============================================

grade_map = {
    "I": 1,
    "II": 2,
    "III": 3,
    "IV": 4,
    "V": 5
}

attendance["grade_clean"] = (
    attendance["grade"]
    .astype("string")
    .str.strip()
    .str.upper()
    .replace(grade_map)
)

# Convert to numeric
attendance["grade_clean"] = pd.to_numeric(
    attendance["grade_clean"],
    errors="coerce"
).astype("Int64")

print("========== GRADE CLEANING AUDIT ==========")

print("Missing after cleaning:",
      attendance["grade_clean"].isna().sum())

print("Invalid grades:",
      (~attendance["grade_clean"].isin(range(1, 11))).sum())

print("\nCleaned grade distribution:")
print(
    attendance["grade_clean"]
    .value_counts()
    .sort_index()
)

========== GRADE CLEANING AUDIT ==========
Missing after cleaning: 0
Invalid grades: 0

Cleaned grade distribution:
grade_clean
1     2790
2     2786
3     2691
4     2864
5     2767
6     1408
7     1433
8     1406
9     1372
10    1283
Name: count, dtype: Int64

In [34]:
# ============================================
# STEP 14: ATTENDANCE COUNT VALIDATION
# ============================================

# Flag impossible attendance records
attendance["impossible_attendance_flag"] = (
    attendance["present_students"] > attendance["total_students"]
)

# Flag other invalid numeric conditions
attendance["invalid_total_students_flag"] = (
    attendance["total_students"] <= 0
)

attendance["invalid_present_students_flag"] = (
    attendance["present_students"] < 0
)

print("========== ATTENDANCE COUNT AUDIT ==========")

print(
    "total_students <= 0:",
    attendance["invalid_total_students_flag"].sum()
)

print(
    "present_students < 0:",
    attendance["invalid_present_students_flag"].sum()
)

print(
    "present_students > total_students:",
    attendance["impossible_attendance_flag"].sum()
)

print("\n========== IMPOSSIBLE RECORDS SAMPLE ==========")

display(
    attendance.loc[
        attendance["impossible_attendance_flag"],
        [
            "record_id",
            "date_clean",
            "school_id_clean",
            "grade_clean",
            "total_students",
            "present_students",
            "teacher_present_clean",
            "marked_by_clean"
        ]
    ].head(20)
)

========== ATTENDANCE COUNT AUDIT ==========
total_students <= 0: 0
present_students < 0: 0
present_students > total_students: 835

========== IMPOSSIBLE RECORDS SAMPLE ==========

,record_id,date_clean,school_id_clean,grade_clean,total_students,present_students,teacher_present_clean,marked_by_clean
8,ATT0002175,2025-05-17,SCH0398,3,260,271,Present,Unknown
12,ATT0007459,2025-05-26,SCH0403,8,181,188,Present,Headmaster
55,ATT0010713,2025-08-17,SCH0235,5,299,315,Present,Class Teacher
100,ATT0003799,2026-11-01,SCH0225,1,92,104,Present,Clerk
132,ATT0007882,2025-11-21,SCH0136,6,137,145,Present,Headmaster
142,ATT0015453,2025-06-30,SCH0202,9,56,69,Present,Clerk
149,ATT0012139,2026-01-25,SCH0417,5,160,176,Present,Headmaster
174,ATT0006557,2025-11-08,SCH0538,3,142,159,Present,Class Teacher
180,NaN,2025-06-12,SCH0231,3,128,139,Present,Clerk
196,ATT0005478,2026-08-02,SCH0305,1,209,225,Present,Headmaster
226,ATT0009490,2025-06-25,SCH0397,2,229,240,Present,Admin
240,ATT0017342,2025-10-15,SCH0403,4,102,111,Issue,Clerk
267,ATT0010978,2025-04-15,SCH0118,4,292,307,Present,Clerk
285,ATT0016028,2026-02-15,SCH0276,3,149,155,Present,Clerk
306,ATT0011119,2025-05-07,SCH0593,5,239,250,Present,Admin
321,ATT0009287,2026-12-02,SCH0201,7,284,303,Present,Clerk
344,ATT0003795,2025-04-11,SCH0137,2,130,139,Present,Headmaster
352,ATT0006428,2025-04-21,SCH0338,3,145,152,Present,Headmaster
353,ATT0010991,2026-03-13,SCH0092,5,134,154,Present,Unknown
376,ATT0015692,2025-12-17,SCH0443,6,251,264,Present,Unknown

In [35]:
# ============================================
# STEP 15: CALCULATE VALID ATTENDANCE RATE
# ============================================

attendance["attendance_rate"] = np.where(
    ~attendance["impossible_attendance_flag"],
    (attendance["present_students"] / attendance["total_students"]) * 100,
    np.nan
)

print("========== ATTENDANCE RATE AUDIT ==========")

print("Valid attendance rates:",
      attendance["attendance_rate"].notna().sum())

print("Excluded due to impossible counts:",
      attendance["attendance_rate"].isna().sum())

print("\nMinimum valid attendance rate:",
      attendance["attendance_rate"].min())

print("Maximum valid attendance rate:",
      attendance["attendance_rate"].max())

print("\nRates above 100%:",
      (attendance["attendance_rate"] > 100).sum())

print("\nRates below 0%:",
      (attendance["attendance_rate"] < 0).sum())

========== ATTENDANCE RATE AUDIT ==========
Valid attendance rates: 19965
Excluded due to impossible counts: 835

Minimum valid attendance rate: 58.139534883720934
Maximum valid attendance rate: 100.0

Rates above 100%: 0

Rates below 0%: 0

In [36]:
# ============================================
# STEP 16: REMOVE EXACT DUPLICATE ROWS
# ============================================

rows_before = len(attendance)

duplicate_count = attendance.duplicated().sum()

attendance = attendance.drop_duplicates().copy()

rows_after = len(attendance)

print("========== DUPLICATE CLEANING ==========")
print("Rows before:", rows_before)
print("Exact duplicate rows removed:", duplicate_count)
print("Rows after:", rows_after)

print("\nRemaining exact duplicates:",
      attendance.duplicated().sum())

print("\nRemaining impossible attendance records:",
      attendance["impossible_attendance_flag"].sum())

print("\nRemaining missing record IDs:",
      attendance["record_id"].isna().sum())

========== DUPLICATE CLEANING ==========
Rows before: 20800
Exact duplicate rows removed: 800
Rows after: 20000

Remaining exact duplicates: 0

Remaining impossible attendance records: 806

Remaining missing record IDs: 405

In [37]:
# ============================================
# STEP 17: RECORD ID AUDIT
# ============================================

print("========== RECORD ID AUDIT ==========")

print("Total rows:", len(attendance))

print("Missing record IDs:",
      attendance["record_id"].isna().sum())

print("Non-missing record IDs:",
      attendance["record_id"].notna().sum())

print("Unique non-missing record IDs:",
      attendance["record_id"].dropna().nunique())

print("Duplicate non-missing record IDs:",
      attendance.loc[
          attendance["record_id"].notna(),
          "record_id"
      ].duplicated().sum())

# Create a flag rather than inventing IDs
attendance["record_id_missing_flag"] = attendance["record_id"].isna()

print("\n========== DUPLICATE RECORD IDs ==========")

duplicate_record_ids = (
    attendance.loc[
        attendance["record_id"].notna(),
        "record_id"
    ]
    .value_counts()
)

duplicate_record_ids = duplicate_record_ids[
    duplicate_record_ids > 1
]

print("Number of duplicated record IDs:",
      len(duplicate_record_ids))

if len(duplicate_record_ids) > 0:
    print("\nSample duplicated IDs:")
    print(duplicate_record_ids.head(20))

========== RECORD ID AUDIT ==========
Total rows: 20000
Missing record IDs: 405
Non-missing record IDs: 19595
Unique non-missing record IDs: 19595
Duplicate non-missing record IDs: 0

========== DUPLICATE RECORD IDs ==========
Number of duplicated record IDs: 0

In [38]:
# ============================================
# STEP 18: FLAG PROXY ATTENDANCE ANOMALIES
# ============================================

attendance["is_sunday"] = (
    attendance["date_clean"].dt.dayofweek == 6
)

attendance["proxy_attendance_flag"] = (
    attendance["is_sunday"]
    & (attendance["attendance_rate"] == 100)
)

print("========== PROXY ATTENDANCE AUDIT ==========")

print("Sunday records:",
      attendance["is_sunday"].sum())

print("Sunday 100% attendance records:",
      attendance["proxy_attendance_flag"].sum())

print(
    "Proxy attendance rate:",
    round(attendance["proxy_attendance_flag"].mean() * 100, 2),
    "%"
)

========== PROXY ATTENDANCE AUDIT ==========
Sunday records: 2878
Sunday 100% attendance records: 979
Proxy attendance rate: 4.9 %

In [39]:
# ============================================
# STEP 19: FINAL ATTENDANCE VALIDATION
# ============================================

print("========== FINAL ATTENDANCE VALIDATION ==========")

print("Rows:", len(attendance))
print("Columns:", len(attendance.columns))

print("\nMissing values:")
print(attendance.isna().sum())

print("\nExact duplicate rows:")
print(attendance.duplicated().sum())

print("\nImpossible attendance records:")
print(attendance["impossible_attendance_flag"].sum())

print("\nProxy attendance records:")
print(attendance["proxy_attendance_flag"].sum())

print("\nValid attendance rates:")
print(attendance["attendance_rate"].notna().sum())

print("\nAttendance rate range:")
print(
    round(attendance["attendance_rate"].min(), 2),
    "to",
    round(attendance["attendance_rate"].max(), 2)
)

print("\nSchool IDs not in School Master:")
print(
    (~attendance["school_id_clean"].isin(df_school["school_id"]))
    .sum()
)

========== FINAL ATTENDANCE VALIDATION ==========
Rows: 20000
Columns: 20

Missing values:
record_id                         405
date                                0
school_id                           0
grade                               0
total_students                      0
present_students                    0
teacher_present                   986
marked_by                        3369
teacher_present_clean               0
marked_by_clean                     0
date_clean                          0
school_id_clean                     0
grade_clean                         0
impossible_attendance_flag          0
invalid_total_students_flag         0
invalid_present_students_flag       0
attendance_rate                   806
record_id_missing_flag              0
is_sunday                           0
proxy_attendance_flag               0
dtype: int64

Exact duplicate rows:
0

Impossible attendance records:
806

Proxy attendance records:
979

Valid attendance rates:
19194

Attendance rate range:
58.14 to 100.0

School IDs not in School Master:
0

In [40]:
# ============================================
# STEP 20: FINAL CLEANED ATTENDANCE DATASET
# ============================================

attendance_cleaned = attendance[
    [
        "record_id",
        "date_clean",
        "school_id_clean",
        "grade_clean",
        "total_students",
        "present_students",
        "teacher_present_clean",
        "marked_by_clean",
        "attendance_rate",
        "impossible_attendance_flag",
        "proxy_attendance_flag",
        "record_id_missing_flag"
    ]
].copy()

# Rename cleaned columns
attendance_cleaned = attendance_cleaned.rename(columns={
    "date_clean": "date",
    "school_id_clean": "school_id",
    "grade_clean": "grade",
    "teacher_present_clean": "teacher_present",
    "marked_by_clean": "marked_by"
})

print("========== FINAL CLEANED ATTENDANCE ==========")
print("Rows:", len(attendance_cleaned))
print("Columns:", len(attendance_cleaned.columns))

print("\nMissing values:")
print(attendance_cleaned.isna().sum())

print("\nDuplicate rows:",
      attendance_cleaned.duplicated().sum())

print("\nImpossible attendance:",
      attendance_cleaned["impossible_attendance_flag"].sum())

print("\nProxy attendance:",
      attendance_cleaned["proxy_attendance_flag"].sum())

========== FINAL CLEANED ATTENDANCE ==========
Rows: 20000
Columns: 12

Missing values:
record_id                     405
date                            0
school_id                       0
grade                           0
total_students                  0
present_students                0
teacher_present                 0
marked_by                       0
attendance_rate               806
impossible_attendance_flag      0
proxy_attendance_flag           0
record_id_missing_flag          0
dtype: int64

Duplicate rows: 0

Impossible attendance: 806

Proxy attendance: 979

In [43]:
import os

print("Current working directory:")
print(os.getcwd())

print("\nFolders/files here:")
print(os.listdir())

Current working directory:
c:\Users\chinm\OneDrive\Pictures\Desktop\education-retention-tracker\notebooks

Folders/files here:
['.gitkeep', '01_eda_and_cleaning.ipynb']

In [46]:
attendance_cleaned.to_csv(
    "../data/cleaned/student_attendance_cleaned.csv",
    index=False
)

print("Cleaned attendance file saved successfully.")

Cleaned attendance file saved successfully.